export const INSERT_RECORD = 'INSERT_RECORD'
export const UPDATE_RECORD = 'UPDATE_RECORD'
export const DELETE_RECORD = 'DELETE_RECORD'

export const LOAD_MONTLY_RECORD = 'LOAD_MONTLY_RECORD'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_BASE_FIREBASE_PATH = 'UPDATE_BASE_FIREBASE_PATH'
